default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: <%= ENV.fetch("DATABASE_USER", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_development") %>

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
